from .Cadeira import Cadeira
from .Turma import Turma
from .Turma_Cadeira import Turma_Cadeira
from .Usuario import Usuario
from .Horario import Horario
from .Controle_Acesso import Controle_Acesso
from .Solicitacao_Acesso_Especial import Solicitacao_Acesso_Especial
from .Falta import Falta
from .Dispensa import Dispensa
from .Nota import Nota
